# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MotorSettings(object):
    def setupUi(self, MotorSettings):
        MotorSettings.setObjectName("MotorSettings")
        MotorSettings.setWindowModality(QtCore.Qt.ApplicationModal)
        MotorSettings.resize(820, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MotorSettings.sizePolicy().hasHeightForWidth())
        MotorSettings.setSizePolicy(sizePolicy)
        MotorSettings.setMinimumSize(QtCore.QSize(0, 0))
        MotorSettings.setMaximumSize(QtCore.QSize(820, 362))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cropped-fav_icon-270x270.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MotorSettings.setWindowIcon(icon)
        MotorSettings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(MotorSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(MotorSettings)
        self.lineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 7, 1, 1, 1)
        self.volume_edit = QtWidgets.QLineEdit(MotorSettings)
        self.volume_edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.volume_edit.setObjectName("volume_edit")
        self.gridLayout.addWidget(self.volume_edit, 5, 1, 1, 1)
        self.setpoint_label = QtWidgets.QLabel(MotorSettings)
        self.setpoint_label.setObjectName("setpoint_label")
        self.gridLayout.addWidget(self.setpoint_label, 4, 0, 1, 1)
        self.ultrasonic_radio = QtWidgets.QRadioButton(MotorSettings)
        self.ultrasonic_radio.setObjectName("ultrasonic_radio")
        self.spraymode_buttongroup = QtWidgets.QButtonGroup(MotorSettings)
        self.spraymode_buttongroup.setObjectName("spraymode_buttongroup")
        self.spraymode_buttongroup.addButton(self.ultrasonic_radio)
        self.gridLayout.addWidget(self.ultrasonic_radio, 3, 2, 1, 1)
        self.milliLmin_radio = QtWidgets.QRadioButton(MotorSettings)
        self.milliLmin_radio.setChecked(True)
        self.milliLmin_radio.setObjectName("milliLmin_radio")
        self.rate_buttongroup = QtWidgets.QButtonGroup(MotorSettings)
        self.rate_buttongroup.setObjectName("rate_buttongroup")
        self.rate_buttongroup.addButton(self.milliLmin_radio)
        self.gridLayout.addWidget(self.milliLmin_radio, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(MotorSettings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.pneumatic_radio = QtWidgets.QRadioButton(MotorSettings)
        self.pneumatic_radio.setChecked(True)
        self.pneumatic_radio.setObjectName("pneumatic_radio")
        self.spraymode_buttongroup.addButton(self.pneumatic_radio)
        self.gridLayout.addWidget(self.pneumatic_radio, 3, 1, 1, 1)
        self.volume_label = QtWidgets.QLabel(MotorSettings)
        self.volume_label.setObjectName("volume_label")
        self.gridLayout.addWidget(self.volume_label, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(MotorSettings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.microstepping_Label = QtWidgets.QLabel(MotorSettings)
        self.microstepping_Label.setObjectName("microstepping_Label")
        self.gridLayout.addWidget(self.microstepping_Label, 1, 0, 1, 1)
        self.maxwidth_Edit = QtWidgets.QLineEdit(MotorSettings)
        self.maxwidth_Edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.maxwidth_Edit.setObjectName("maxwidth_Edit")
        self.gridLayout.addWidget(self.maxwidth_Edit, 2, 1, 1, 1)
        self.delay_Edit = QtWidgets.QLineEdit(MotorSettings)
        self.delay_Edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.delay_Edit.setObjectName("delay_Edit")
        self.gridLayout.addWidget(self.delay_Edit, 0, 1, 1, 1)
        self.sixteen_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.sixteen_microstep.setObjectName("sixteen_microstep")
        self.microstepping_buttongroup = QtWidgets.QButtonGroup(MotorSettings)
        self.microstepping_buttongroup.setObjectName("microstepping_buttongroup")
        self.microstepping_buttongroup.addButton(self.sixteen_microstep)
        self.gridLayout.addWidget(self.sixteen_microstep, 1, 5, 1, 1)
        self.eight_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.eight_microstep.setObjectName("eight_microstep")
        self.microstepping_buttongroup.addButton(self.eight_microstep)
        self.gridLayout.addWidget(self.eight_microstep, 1, 4, 1, 1)
        self.one_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.one_microstep.setChecked(False)
        self.one_microstep.setAutoRepeat(False)
        self.one_microstep.setObjectName("one_microstep")
        self.microstepping_buttongroup.addButton(self.one_microstep)
        self.gridLayout.addWidget(self.one_microstep, 1, 1, 1, 1)
        self.maxwidth_Label = QtWidgets.QLabel(MotorSettings)
        self.maxwidth_Label.setObjectName("maxwidth_Label")
        self.gridLayout.addWidget(self.maxwidth_Label, 2, 0, 1, 1)
        self.delay_Label = QtWidgets.QLabel(MotorSettings)
        self.delay_Label.setObjectName("delay_Label")
        self.gridLayout.addWidget(self.delay_Label, 0, 0, 1, 1)
        self.two_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.two_microstep.setChecked(False)
        self.two_microstep.setObjectName("two_microstep")
        self.microstepping_buttongroup.addButton(self.two_microstep)
        self.gridLayout.addWidget(self.two_microstep, 1, 2, 1, 1)
        self.four_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.four_microstep.setChecked(True)
        self.four_microstep.setObjectName("four_microstep")
        self.microstepping_buttongroup.addButton(self.four_microstep)
        self.gridLayout.addWidget(self.four_microstep, 1, 3, 1, 1)
        self.thirtytwo_microstep = QtWidgets.QRadioButton(MotorSettings)
        self.thirtytwo_microstep.setObjectName("thirtytwo_microstep")
        self.microstepping_buttongroup.addButton(self.thirtytwo_microstep)
        self.gridLayout.addWidget(self.thirtytwo_microstep, 1, 6, 1, 1)
        self.setpoint_edit = QtWidgets.QLineEdit(MotorSettings)
        self.setpoint_edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.setpoint_edit.setObjectName("setpoint_edit")
        self.gridLayout.addWidget(self.setpoint_edit, 4, 1, 1, 1)
        self.spraymode_label = QtWidgets.QLabel(MotorSettings)
        self.spraymode_label.setObjectName("spraymode_label")
        self.gridLayout.addWidget(self.spraymode_label, 3, 0, 1, 1)
        self.milliLhour_radio = QtWidgets.QRadioButton(MotorSettings)
        self.milliLhour_radio.setObjectName("milliLhour_radio")
        self.rate_buttongroup.addButton(self.milliLhour_radio)
        self.gridLayout.addWidget(self.milliLhour_radio, 6, 3, 1, 1)
        self.dispense_rate_label = QtWidgets.QLabel(MotorSettings)
        self.dispense_rate_label.setObjectName("dispense_rate_label")
        self.gridLayout.addWidget(self.dispense_rate_label, 6, 0, 1, 1)
        self.microLhour_radio = QtWidgets.QRadioButton(MotorSettings)
        self.microLhour_radio.setObjectName("microLhour_radio")
        self.rate_buttongroup.addButton(self.microLhour_radio)
        self.gridLayout.addWidget(self.microLhour_radio, 6, 5, 1, 1)
        self.milliL_radio = QtWidgets.QRadioButton(MotorSettings)
        self.milliL_radio.setChecked(True)
        self.milliL_radio.setObjectName("milliL_radio")
        self.volume_buttongroup = QtWidgets.QButtonGroup(MotorSettings)
        self.volume_buttongroup.setObjectName("volume_buttongroup")
        self.volume_buttongroup.addButton(self.milliL_radio)
        self.gridLayout.addWidget(self.milliL_radio, 5, 2, 1, 1)
        self.microLmin_radio = QtWidgets.QRadioButton(MotorSettings)
        self.microLmin_radio.setObjectName("microLmin_radio")
        self.rate_buttongroup.addButton(self.microLmin_radio)
        self.gridLayout.addWidget(self.microLmin_radio, 6, 4, 1, 1)
        self.microL_radio = QtWidgets.QRadioButton(MotorSettings)
        self.microL_radio.setChecked(False)
        self.microL_radio.setObjectName("microL_radio")
        self.volume_buttongroup.addButton(self.microL_radio)
        self.gridLayout.addWidget(self.microL_radio, 5, 3, 1, 1)
        self.dispense_rate_edit = QtWidgets.QLineEdit(MotorSettings)
        self.dispense_rate_edit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.dispense_rate_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dispense_rate_edit.setClearButtonEnabled(False)
        self.dispense_rate_edit.setObjectName("dispense_rate_edit")
        self.gridLayout.addWidget(self.dispense_rate_edit, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(MotorSettings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(MotorSettings)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 8, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settingsButtonBox = QtWidgets.QDialogButtonBox(MotorSettings)
        self.settingsButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.settingsButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.settingsButtonBox.setCenterButtons(False)
        self.settingsButtonBox.setObjectName("settingsButtonBox")
        self.horizontalLayout.addWidget(self.settingsButtonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MotorSettings)
        self.settingsButtonBox.accepted.connect(MotorSettings.accept)
        self.settingsButtonBox.rejected.connect(MotorSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(MotorSettings)

    def retranslateUi(self, MotorSettings):
        _translate = QtCore.QCoreApplication.translate
        MotorSettings.setWindowTitle(_translate("MotorSettings", "Spray Settings"))
        self.setpoint_label.setText(_translate("MotorSettings", "Hotplate Setpoint (Celsius)"))
        self.ultrasonic_radio.setText(_translate("MotorSettings", "Ultrasonic"))
        self.milliLmin_radio.setText(_translate("MotorSettings", "milliL/min"))
        self.label.setText(_translate("MotorSettings", "Pause Time (sec)"))
        self.pneumatic_radio.setText(_translate("MotorSettings", "Pneumatic"))
        self.volume_label.setText(_translate("MotorSettings", "Volume To Dispense"))
        self.label_4.setText(_translate("MotorSettings", "(200-500)"))
        self.microstepping_Label.setText(_translate("MotorSettings", "Microstepping"))
        self.sixteen_microstep.setText(_translate("MotorSettings", "1/16"))
        self.eight_microstep.setText(_translate("MotorSettings", "1/8"))
        self.one_microstep.setText(_translate("MotorSettings", "1/1"))
        self.maxwidth_Label.setText(_translate("MotorSettings", "Track Length (inches)"))
        self.delay_Label.setText(_translate("MotorSettings", "Motor Delay (microsec)"))
        self.two_microstep.setText(_translate("MotorSettings", "1/2"))
        self.four_microstep.setText(_translate("MotorSettings", "1/4"))
        self.thirtytwo_microstep.setText(_translate("MotorSettings", "1/32"))
        self.spraymode_label.setText(_translate("MotorSettings", "Spray Mode"))
        self.milliLhour_radio.setText(_translate("MotorSettings", "milliL/hour"))
        self.dispense_rate_label.setText(_translate("MotorSettings", "Dispense Rate"))
        self.microLhour_radio.setText(_translate("MotorSettings", "microL/hour"))
        self.milliL_radio.setText(_translate("MotorSettings", "milliliters"))
        self.microLmin_radio.setText(_translate("MotorSettings", "microL/min"))
        self.microL_radio.setText(_translate("MotorSettings", "microliters"))
        self.label_2.setText(_translate("MotorSettings", "Spray Width (inches) "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MotorSettings = QtWidgets.QDialog()
    ui = Ui_MotorSettings()
    ui.setupUi(MotorSettings)
    MotorSettings.show()
    sys.exit(app.exec_())

